# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: install missing pkg
      run: |
        sudo apt-get install libglu1
        sudo apt-get install libxi6 libgconf-2-4
        sudo apt-get install  sudo apt-get install libjpeg-dev libpng-dev libweb-dev
        sudo ldconfig
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install # will run `yarn install` command
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: generate # will run `yarn run generate` command
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: deploy # will run `yarn run deploy` command
